trigger:
  paths:
    include:
      - internal/account

resources:
  - repo: self
pool: "Azure Pipelines"

variables:
  image-repo: 'seineo/only-account'

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: CmdLine@2
            inputs:
              script: ' x=`echo "$(Build.SourceVersion)" | head -c 8`; echo "##vso[task.setvariable variable=SHORT_COMMIT]$x"'

          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: "$(image-repo)"
              command: 'buildAndPush'
              tags: '$(Build.BuildNumber)-$(SHORT_COMMIT)'
#              buildContext: '.'
              Dockerfile: 'internal/account/Dockerfile'

          #          - script: |
          #              docker rmi $(image-repo):'$(Build.BuildNumber)-$(SHORT_COMMIT)'
          #            displayName: 'rm image'

          - script: |
              curl --location --request PUT --X PUT 'http://cd.bupt.site:30303/api/v1/deployments' --header 'Content-Type: application/json'  --header 'key: WloKNGGRageouISkabeoNfLLJYLQVKUxtFIsnMiaGOlaIuckVNqhPeUZyNUuGtJz'    --header 'value: token-lyw-only-account-only-account-e6f6354a'      --data '{ "namespace":"lyw","deployment":"only-account","container": "only-account","image": "registry.cn-beijing.aliyuncs.com/$(image-repo):$(Build.BuildNumber)-$(SHORT_COMMIT)"}'
            displayName: 'send curl'
