trigger:
  paths:
    include:
      - internal/email
      - internal/common
      - email-pipelines.yml

resources:
  - repo: self
pool: "Azure Pipelines"

variables:
  image-repo: 'bupt2018/only-email'

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: CmdLine@2
            inputs:
              script: ' x=`echo "$(Build.SourceVersion)" | head -c 8`; echo "##vso[task.setvariable variable=SHORT_COMMIT]$x"'

          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: "$(image-repo)"
              command: 'buildAndPush'
              tags: '$(Build.BuildNumber)-$(SHORT_COMMIT)'
              buildContext: '.'
              Dockerfile: 'internal/email/Dockerfile'

          #          - script: |
          #              docker rmi $(image-repo):'$(Build.BuildNumber)-$(SHORT_COMMIT)'
          #            displayName: 'rm image'

          - script: |
              curl --location --request PUT --X PUT 'http://cd.bupt.site:30303/api/v1/deployments' --header 'Content-Type: application/json'  --header 'key: QDvIWzmkCWMrkRIxReuqzGGHwMGGhopuGthmlasqToqAjJMMNHfyCIObaXCMNvMw'    --header 'value: token-lyw-only-email-only-email-d6cb9fe0'      --data '{ "namespace":"lyw","deployment":"only-email","container": "only-email","image": "registry.cn-beijing.aliyuncs.com/$(image-repo):$(Build.BuildNumber)-$(SHORT_COMMIT)"}'
            displayName: 'send curl'
