apiVersion: apps/v1
kind: Deployment
metadata:
  name: only-account
spec:
  selector:
    matchLabels:
      app: only-account
  template:
    metadata:
      labels:
        app: only-account
    spec:
      containers:
      - name: only-account
        image: seineo/only-account
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: only-account
spec:
  selector:
    app: only-account
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: only-account-mysql
spec:
  selector:
    matchLabels:
      app: only-account-mysql
  template:
    metadata:
      labels:
        app: only-account-mysql
    spec:
      containers:
      - name: only-account-mysql
        image: mysql:8.2.0
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: only-account-mysql
spec:
  selector:
    app: only-account-mysql
  ports:
  - port: 3306
    targetPort: 3306
