apiVersion: apps/v1
kind: Deployment
metadata:
  name: only-redis
spec:
  selector:
    matchLabels:
      app: only-redis
  template:
    metadata:
      labels:
        app: only-redis
    spec:
      containers:
      - name: only-redis
        image: redis:7.2.3
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: only-redis
spec:
  selector:
    app: only-redis
  ports:
  - port: 6379
    targetPort: 6379


